import { Database } from './supabase/types';

type Project = Database['public']['Tables']['projects']['Row'];
type PunchItem = Database['public']['Tables']['punch_items']['Row'];
type DailyLog = Database['public']['Tables']['daily_logs']['Row'];
type WarehouseInventory = Database['public']['Tables']['warehouse_inventory']['Row'];
type PurchaseOrder = Database['public']['Tables']['purchase_orders']['Row'];
type Message = Database['public']['Tables']['messages']['Row'];
type Notification = Database['public']['Tables']['notifications']['Row'];

// Helper to generate dates relative to today
const today = new Date();
const daysAgo = (days: number) => new Date(today.getTime() - days * 86400000).toISOString();
const daysFromNow = (days: number) => new Date(today.getTime() + days * 86400000).toISOString();

export const DEMO_PROJECTS: Project[] = [
    {
        id: 101,
        key: 'PRJ-101',
        name: 'Downtown Loft Renovation',
        client: 'Sarah Jenkins',
        address: '123 Main St, Apt 4B, Metro City, NY 10012',
        sqft: 1200,
        type: 'Residential',
        value: 45000,
        progress: 65,
        status: 'active',
        start_date: daysAgo(14),
        due_date: daysFromNow(7),
        crew_id: 'crew-1',
        created_by: 'demo-user',
        created_at: daysAgo(15),
        updated_at: daysAgo(1),
        deleted_at: null,
        deleted_by: null
    },
    {
        id: 102,
        key: 'PRJ-102',
        name: 'TechHub Office HQ',
        client: 'TechHub Inc.',
        address: '450 Innovation Blvd, Silicon Valley, CA 94025',
        sqft: 15000,
        type: 'Commercial',
        value: 1250000,
        progress: 30,
        status: 'active',
        start_date: daysAgo(30),
        due_date: daysFromNow(60),
        crew_id: 'crew-2',
        created_by: 'demo-user',
        created_at: daysAgo(35),
        updated_at: daysAgo(2),
        deleted_at: null,
        deleted_by: null
    },
    {
        id: 103,
        key: 'PRJ-103',
        name: 'Lakeside Cottage',
        client: 'Robert Ford',
        address: '88 Lake View Dr, Tahoe, CA 96150',
        sqft: 2500,
        type: 'Residential',
        value: 85000,
        progress: 100,
        status: 'completed',
        start_date: daysAgo(60),
        due_date: daysAgo(10),
        crew_id: 'crew-1',
        created_by: 'demo-user',
        created_at: daysAgo(65),
        updated_at: daysAgo(10),
        deleted_at: null,
        deleted_by: null
    }
];

export const DEMO_PUNCH_ITEMS: PunchItem[] = [
    {
        id: 1,
        project_id: 101,
        text: 'Scratch on hallway hardwood',
        priority: 'high',
        status: 'open',
        category: 'damage',
        reporter: 'Sarah Jenkins',
        reporter_id: 'client-sarah',
        reported_date: daysAgo(2),
        assigned_to: 'Mike Installer',
        assigned_to_id: 'user-mike',
        assigned_date: daysAgo(1),
        assigned_by: 'Demo User',
        location: 'Hallway',
        room: 'Entry',
        area: 'Floor',
        due: daysFromNow(1),
        due_time: null,
        completed: false,
        completed_by: null,
        completed_by_id: null,
        completed_date: null,
        verification_required: true,
        verified_by: null,
        verified_by_id: null,
        verified_date: null,
        notes: 'Client noticed during evening walk through',
        internal_notes: 'Need to bring repair kit',
        tags: ['repair', 'hardwood'],
        estimated_hours: 2,
        actual_hours: null,
        visible_to_client: true,
        client_approval_required: true,
        walkthrough_session_id: null,
        created_at: daysAgo(2),
        updated_at: daysAgo(2),
        deleted_at: null,
        deleted_by: null
    },
    {
        id: 2,
        project_id: 101,
        text: 'Missing transition strip',
        priority: 'medium',
        status: 'completed',
        category: 'transition',
        reporter: 'Demo User',
        reporter_id: '99',
        reported_date: daysAgo(5),
        assigned_to: 'Mike Installer',
        assigned_to_id: 'user-mike',
        assigned_date: daysAgo(4),
        assigned_by: 'Demo User',
        location: 'Kitchen to Dining',
        room: 'Kitchen',
        area: 'Threshold',
        due: daysAgo(2),
        due_time: null,
        completed: true,
        completed_by: 'Mike Installer',
        completed_by_id: 'user-mike',
        completed_date: daysAgo(2),
        verification_required: false,
        verified_by: 'Demo User',
        verified_by_id: '99',
        verified_date: daysAgo(1),
        notes: null,
        internal_notes: null,
        tags: ['transition'],
        estimated_hours: 1,
        actual_hours: 0.5,
        visible_to_client: true,
        client_approval_required: false,
        walkthrough_session_id: null,
        created_at: daysAgo(5),
        updated_at: daysAgo(1),
        deleted_at: null,
        deleted_by: null
    },
    {
        id: 3,
        project_id: 102,
        text: 'Carpet bubbling in conference room',
        priority: 'critical',
        status: 'open',
        category: 'installation',
        reporter: 'TechHub PM',
        reporter_id: 'client-techhub',
        reported_date: daysAgo(1),
        assigned_to: null,
        assigned_to_id: null,
        assigned_date: null,
        assigned_by: null,
        location: 'Conf Room A',
        room: 'Conference Room',
        area: 'Center',
        due: daysFromNow(0),
        due_time: '14:00',
        completed: false,
        completed_by: null,
        completed_by_id: null,
        completed_date: null,
        verification_required: true,
        verified_by: null,
        verified_by_id: null,
        verified_date: null,
        notes: 'Hazard potential',
        internal_notes: 'Might need restretch',
        tags: ['safety', 'carpet'],
        estimated_hours: 4,
        actual_hours: null,
        visible_to_client: true,
        client_approval_required: true,
        walkthrough_session_id: null,
        created_at: daysAgo(1),
        updated_at: daysAgo(1),
        deleted_at: null,
        deleted_by: null
    }
];

export const DEMO_DAILY_LOGS: DailyLog[] = [
    {
        id: 'log-1',
        project_id: 101,
        date: daysAgo(0).split('T')[0],
        total_crew_count: 3,
        total_hours: 24,
        overtime_hours: 0,
        work_completed: 'Completed living room hardwood installation. Started baseboards.',
        sqft_completed: 450,
        phase: 'install',
        areas_worked: ['Living Room', 'Hallway'],
        percent_complete: 65,
        weather: 'sunny',
        temperature: 72,
        humidity: 45,
        has_delays: false,
        total_delay_minutes: 0,
        safety_notes: 'All PPE worn. Safety meeting held at 8am.',
        incident_reported: false,
        incident_id: null,
        client_on_site: true,
        client_name: 'Sarah Jenkins',
        client_notes: 'Client happy with progress',
        site_conditions: 'Clean and dry',
        signed_by: 'Foreman Joe',
        signed_by_id: 'user-joe',
        signed_at: daysAgo(0),
        signature_data: 'signed',
        created_by: 'Foreman Joe',
        created_by_id: 'user-joe',
        created_at: daysAgo(0),
        updated_at: daysAgo(0),
        last_modified_by: null,
        submitted_offline: false,
        synced_at: daysAgo(0),
        deleted_at: null,
        deleted_by: null
    },
    {
        id: 'log-2',
        project_id: 101,
        date: daysAgo(1).split('T')[0],
        total_crew_count: 3,
        total_hours: 24,
        overtime_hours: 0,
        work_completed: 'Subfloor prep completed. Materials acclimated.',
        sqft_completed: 600,
        phase: 'prep',
        areas_worked: ['Living Room', 'Dining Room'],
        percent_complete: 40,
        weather: 'cloudy',
        temperature: 68,
        humidity: 50,
        has_delays: true,
        total_delay_minutes: 45,
        safety_notes: 'Dust containment set up.',
        incident_reported: false,
        incident_id: null,
        client_on_site: false,
        client_name: null,
        client_notes: null,
        site_conditions: 'Subfloor required leveling',
        signed_by: 'Foreman Joe',
        signed_by_id: 'user-joe',
        signed_at: daysAgo(1),
        signature_data: 'signed',
        created_by: 'Foreman Joe',
        created_by_id: 'user-joe',
        created_at: daysAgo(1),
        updated_at: daysAgo(1),
        last_modified_by: null,
        submitted_offline: false,
        synced_at: daysAgo(1),
        deleted_at: null,
        deleted_by: null
    }
];

export const DEMO_INVENTORY: WarehouseInventory[] = [
    {
        id: 'inv-1',
        sku: 'OAK-NAT-5',
        name: 'Natural White Oak 5"',
        description: 'Engineered hardwood, 5 inch plank, natural finish',
        category: 'Hardwood',
        manufacturer: 'Forest Floor',
        unit: 'sqft',
        quantity_on_hand: 1540,
        quantity_reserved: 450,
        quantity_available: 1090,
        reorder_point: 500,
        reorder_qty: 1000,
        lead_time_days: 14,
        unit_cost: 4.50,
        last_cost: 4.50,
        avg_cost: 4.45,
        default_location_id: 'A-12',
        created_at: daysAgo(100),
        updated_at: daysAgo(5),
        deleted_at: null,
        deleted_by: null
    },
    {
        id: 'inv-2',
        sku: 'ADH-PRO-5G',
        name: 'ProBond Advesive 5G',
        description: 'High performance wood adhesive',
        category: 'Supplies',
        manufacturer: 'ProBond',
        unit: 'pail',
        quantity_on_hand: 12,
        quantity_reserved: 4,
        quantity_available: 8,
        reorder_point: 10,
        reorder_qty: 20,
        lead_time_days: 3,
        unit_cost: 125.00,
        last_cost: 128.00,
        avg_cost: 126.50,
        default_location_id: 'B-04',
        created_at: daysAgo(100),
        updated_at: daysAgo(2),
        deleted_at: null,
        deleted_by: null
    }
];

export const DEMO_PURCHASE_ORDERS: PurchaseOrder[] = [
    {
        id: 'po-1',
        project_id: 101,
        po_number: 'PO-2024-001',
        vendor_id: 1,
        vendor_name: 'Metro Flooring Supply',
        status: 'received',
        order_date: daysAgo(20),
        expected_delivery: daysAgo(15),
        actual_delivery: daysAgo(15),
        subtotal: 5400,
        tax: 432,
        shipping: 150,
        total: 5982,
        notes: 'Materials for Downtown Loft',
        created_by: 'Demo User',
        approved_by: 'Manager Mike',
        created_at: daysAgo(20),
        updated_at: daysAgo(15),
        deleted_at: null,
        deleted_by: null
    },
    {
        id: 'po-2',
        project_id: 102,
        po_number: 'PO-2024-002',
        vendor_id: 2,
        vendor_name: 'Pro Tools Inc',
        status: 'ordered',
        order_date: daysAgo(2),
        expected_delivery: daysFromNow(5),
        actual_delivery: null,
        subtotal: 1200,
        tax: 96,
        shipping: 50,
        total: 1346,
        notes: 'Specialty equipment for TechHub',
        created_by: 'Demo User',
        approved_by: 'Manager Mike',
        created_at: daysAgo(2),
        updated_at: daysAgo(2),
        deleted_at: null,
        deleted_by: null
    }
];

export const DEMO_MESSAGES: Message[] = [
    {
        id: 1,
        project_id: 101,
        sender_id: 'client-sarah',
        sender_name: 'Sarah Jenkins',
        sender_role: 'client',
        content: 'Love the progress so far! When will the team be back tomorrow?',
        type: 'text',
        thread_id: null,
        reply_count: 1,
        mentions: [],
        created_at: daysAgo(1)
    },
    {
        id: 2,
        project_id: 101,
        sender_id: '99',
        sender_name: 'Demo User',
        sender_role: 'pm',
        content: 'Glad you like it, Sarah! We will be there at 8 AM sharp.',
        type: 'text',
        thread_id: 1,
        reply_count: 0,
        mentions: [],
        created_at: daysAgo(0) // TODAY
    }
];

export const DEMO_NOTIFICATIONS: Notification[] = [
    {
        id: 'notif-1',
        user_id: '99',
        type: 'message',
        title: 'New Message',
        message: 'Sarah Jenkins: Love the progress so far!',
        link: '/projects/101/messages',
        action_url: null,
        project_id: 101,
        read: false,
        created_at: daysAgo(1)
    },
    {
        id: 'notif-2',
        user_id: '99',
        type: 'task',
        title: 'Task Due Soon',
        message: 'Verify subfloor prep for TechHub HQ',
        link: '/projects/102/tasks',
        action_url: null,
        project_id: 102,
        read: true,
        created_at: daysAgo(2)
    }
];
